nteract/commuter

- packages/commuter-client/package.json
- packages/commuter-client/src/Preview.js
- packages/commuter-client/src/index.js
- packages/commuter-directory-listing/package.json
- packages/commuter-directory-listing/src/components/Table.js
- [NotebookPreview](https://github.com/nteract/notebook-preview) has styles for generic elements like [\<td\>](https://github.com/nteract/notebook-preview/blob/master/styles/main.css#L45) which is messing up with sematicUI styles. So skip import of `main.css` from NotebookPreview for time being.
> Wire up NotebookPreview for static display

- README.md
Noticed it was loading a bit funny on the README, had it point to the running demo.
> fix image for Heroku deployment badge

- packages/commuter-client/package.json
- packages/commuter-client/src/Preview.js
This renders the styling for notebooks:
However, we need to change the CSS for nteract to scope to outputs, etc. properly, otherwise it messes up the dashboard view:
This is not intended to be merged, using this to help me cement what I'm going to do next for notebook preview CSS.
Things to do (externally to this repository):
---------------------------
Using incognito mode in honor of dark top, light bottoms day on GitHub.
> Render notebook styles

- packages/commuter-server/src/routes/contents.js
Follow on to #70.
Looking at the `services/s3` module here, the interface on the s3 service operations should likely have the first argument be the `S3` object (and if necessary, the user could `bind` it).
> bring isDir into s3 services package

- packages/commuter-client/src/Discovery.js
Otherwise there's two spaces between "1 month ago" and "by kylek"
> Delete extraneous space

- packages/commuter-server/package.json
- packages/commuter-server/src/routes/files.js
- packages/commuter-server/src/routes/index.js
In order to fully do #88, #43 we need an endpoint that serves files directly as is. This endpoint is not intended for users to visit directly (same as jupyter), yet is how we'll load images on relative paths.
> proxy /files/ from s3, like jupyter server

- packages/commuter-server/src/routes/view.js
Setting up a `/view/` route. When a user visits `/view/some/test.rmd.html` that includes a relative asset like this:
```html
```
It will
* Attempt to load `/view/some/plot.png`
* Get redirected to `/files/some/plot.png`
Result is rendered appropriately, even though we're iframing the HTML.
This matches the mechanics of the jupyter notebook server (though that uses `/notebooks/` and `/view/`).
> ☯️ create a /view/ route as the yin to /files/ yang

- packages/commuter-server/src/services/s3.js
Bringing in some fixes from #88 since that's not ready until I finish adapting the express + create-react-app setup. I'll be opening another PR for the `/view/` route.
> fix(contents): return non-notebook as string for contents API

- packages/commuter-client/package.json
- packages/commuter-client/src/Commuter.js
- packages/commuter-client/src/Notebook.js
- packages/commuter-client/src/index.js
- packages/commuter-client/src/strip-view.js
- packages/commuter-directory-listing/package.json
- packages/commuter-directory-listing/src/DirectoryListing.js
Switching over to React Router v4, handling the `/view/` routes. A worthy refactor after this is to make a top level `Contents` component rather than having separate handling amongst `Commuter` and `Notebook`. There's a lot of action repetition when there shouldn't be. Same thing for the path cleansing.
> Handle /view/ paths

- packages/commuter-server/src/services/s3.js
This catches when, for instance, the nyc taxi notebook comes back with only _part_ of the data.
> wrap our JSON.parse from s3 notebook in try/catch

- packages/commuter-client/package.json
This has been fixed in nteract/nteract, however there is an incident on npm preventing us from receiving the update. For now, let's go ahead and pin codemirror so that commuter master is fixed.
> pin codemirror to 5.24.x

- packages/commuter-client/src/Contents.js
redirect users to the `/files/` endpoint for non-html, non-notebook content
> redirect non-html content

- packages/commuter-server/src/routes/api/contents.js
- packages/commuter-server/src/routes/api/index.js
- packages/commuter-server/src/routes/api/v1/discovery.js
- packages/commuter-server/src/routes/index.js
- packages/commuter-server/src/server.js
This switches up how we set the default content type to only do it on `/api/` while also making our directories organized around the routes.
> keep content types accurate by configuring router

- packages/commuter-server/src/routes/view.js
Allows JSON and Markdown to be viewed at `/view/`, unknown files still get served on `/files/`.
> Allow JSON and Markdown through the view route

- packages/commuter-client/src/Contents.js
- packages/commuter-client/src/zeppelin.js
Took the nteract components and a bit of table tomfoolery with (one of) their table attributes to create a rendition of the zeppelin notebook format:
In the future, I'd like to convert their table format over to the data resource so that we can use the transform from https://github.com/nteract/nteract/pull/1534 and get our fully interactive grid. :smile:
---------------------------
An aside on the tables, they encode it three different ways -- I assume to handle different versions of zeppelin over time...
> More renderers: JSON, Zeppelin

- packages/commuter-client/src/Contents.js
- packages/commuter-client/src/zeppelin.js
Sometimes Zeppelin has MSG, sometimes it doesn't.
> Check for MSG on the label

- packages/commuter-server/src/routes/files.js
> set the prefix via config.basePath

- packages/commuter-client/src/reducers/index.js
- packages/commuter-directory-listing/src/DirectoryListing.js
As suggested in #144, moving where the hidden files are trimmed to the reducer.
> chore(hiddenFiles): trim hidden files in the reducer instead of directory listing component

- packages/commuter-client/src/reducers/index.js
- packages/commuter-directory-listing/src/DirectoryListing.js
- packages/commuter-server/src/content-providers/local/contents.js
This also handles when a directory entry shouldn't be in the listing because the stat call failed.
> Process and handle FS errors with 404s

- packages/commuter-client/src/contents/zeppelin.js
Only show the rendered markdown when on a markdown cell for Zeppelin. Makes for a nice clean report-like view.
> When Zepp markdown cell, only show result

- packages/commuter-breadcrumb/__tests__/BreadCrumb.test.js
- packages/commuter-breadcrumb/package.json
- packages/commuter-breadcrumb/src/BreadCrumb.js
- packages/commuter-client/src/contents/index.js
- packages/commuter-directory-listing/src/DirectoryListing.js
The `onClick` handling that was in here didn't handle all the normal browser cases like being able to command-click to open links in new tabs. Since I'd rather not make this more complicated, I'd rather just rely on `<Link>`. This simplifies our setup to assume we rely on `react-router-dom`.
> Restore proper links

- packages/frontend/components/contents/directory-listing.js
- packages/frontend/theme.js
Prompted by suggestions from @sushantanand, here's an initial grouped view.
It only shows when there are more than 20 rows.
What do you think?
> group content by letter when a large directory

- packages/frontend/components/contents/directory-listing.js
Couple tweaks based on running this in production:
* When there's a directory of notebooks that all start with the same letter (a batch run through papermill in parallel for instance) it looks really silly to have the grouped heading
* Twenty files was far too small to decide to do grouping
* If the group object isn't created in a sorted order (likely because of upper and lowercase files) then the resulting "normalized" grouping will end up in a funny ascii order. Example "P _ A B C D..."
I've addressed each of these all together here.
> Grouped directory listing improvements

- packages/frontend/.gitignore
- packages/frontend/package.json
- packages/frontend/pages/_document.js
- packages/server/examples/table-with-schema.ipynb
Globally included mathjax in the page, which I'm not stoked about. I do know our config requires an imperative call at least, which is controlled by the mathjax-electron module. Our name for our version of mathjax is a bit of a misnomer, I wonder if we should rename @lgeiger (it works well in Chrome at least).
One day I'd love a nice trim mathjax scoped to the notebook. ;)
Closes #174
> include mathjax on the commuter page

- packages/frontend/components/contents/directory-listing.js
I find it hilarious how I've continued to come back to fix this... 😝 
Since I was using `Object.keys(groups)` in two places, I've made sure to sort it just once and reuse the group names.
/cc @jessicasw
> sort when displaying header

- packages/frontend/components/header.js
- packages/frontend/pages/discover.js
- packages/frontend/pages/index.js
- packages/frontend/pages/view.js
/cc @parente 
This makes discovery a togglable navigation component for when `discoveryEnabled` is set. Note this _only_ affects the component here, and I haven't figured a decent approach to disabling discovery when it's not configured.
> allow toggling discovery in the header

- packages/frontend/icons/octicons.js
This seems to be related to styled-jsx, but it's not 100% clear why. At
any rate, just making the spread operation fixes the issue.
Closes: #238
> fix: "complex" spread for props was failing.

- flow-typed/npm/fs-extra_vx.x.x.js
- packages/server/package.json
- packages/server/src/content-providers/local/contents.js
- packages/server/src/content-providers/local/fs.js
For testing it was useful to be able to POST files to the local backend.
---
Semi related question: I think the jupyter notebook uses PUT when you hit "Save" to update the contents of the notebook. commuter seems to conform to the contents provider API except you POST files instead of PUTing. Is the resemblance to the contents API accidental or does it actually not matter or just not implemented?
> Add support for POSTing files to the local contents provider

- README.md
- package.json
- yarn.lock
In setting up this project locally at PyCon sprints, I found the following commands to be broken:
- `yarn app:commuter`
- `yarn test`
This PR updates the instructions to use `dev` instead of `app:commuter` and adds `jest` as the test runner.
> Fix dev tasks

- README.md
- backend/config.js
- backend/content-providers/s3/files.js
* related issue : https://github.com/nteract/commuter/issues/262
* You can set new environment variable(`COMMUTER_S3_ENDPOINT`) to use your own S3 endpoint.
> Make S3 endpoint configurable

- README.md
* Add a description of GCP credentials to README
* The 4th step in https://www.npmjs.com/package/@google-cloud/storage#before-you-begin is to configure this environment variable
* For GCS backend
> Add a description of GCP credentials to README

- README.md
- backend/config.js
Hi, 
I was trying to configure Commuter with the S3 compatible object storage [MinIO](https://min.io/) however I would get the following error:
```
[Error [AjaxError]: ajax error 500] {
xhr: {
UNSENT: 0,
OPENED: 1,
HEADERS_RECEIVED: 2,
LOADING: 3,
DONE: 4,
readyState: 4,
onreadystatechange: [Function: xhrReadyStateChange] {
subscriber: [AjaxSubscriber],
progressSubscriber: undefined,
request: [Object]
},
responseText: '{"message":"getaddrinfo ENOTFOUND <MY_BUCKET_NAME_REDACTED>.<MY_ENDPOINT_REDACTED>: ","reason":"NetworkingError"}',
responseXML: '',
status: 500,
statusText: null,
withCredentials: false,
open: [Function (anonymous)],
setDisableHeaderCheck: [Function (anonymous)],
setRequestHeader: [Function (anonymous)],
getResponseHeader: [Function (anonymous)],
getAllResponseHeaders: …
```
> add an option to enable s3ForcePathStyle

- .github/workflows/yarn-test.yml
- README.md
This PR introduces automated testing on each pull request and commit. This is to simplify development flows for people without suitable dev environments.
I have two questions:
1. Tests are triggered using Node 10 and 12 (v14 failed), are there any other versions we want to test against? The README doesn't quite describe what environments are supported.
2. Do we want to test other things? Like a production build?
Thanks!
> Automatic testing via GitHub Actions

- .dockerignore
- Dockerfile
- Dockerfile.dev
- README.md
Adds a Dockerfile for running commuter in a production environment
There is an old PR still open for adding simple Docker support, but that appears more suitable for local development: https://github.com/nteract/commuter/issues/188
This PR is intended to build a Docker container suitable for publishing to Dockerhub (or other registry) and be run in a production environment such as Kubernetes.
It can be tested locally as follows:
```
checkout this branch
docker build --tag commuter:latest .
docker run \
--publish 4000:4000 \
--mount type=bind,source=/home/username/work/commuter/examples,target=/examples \
--env COMMUTER_LOCAL_STORAGE_BASEDIRECTORY=/examples \
commuter:latest
```
*or* (use my prebuilt image)
```
checkout commuter master branch
docker run \
--publish 4000:4000 \
--mount …
```
> Add Dockerfile

- src/backend/config.js
I encountered the same issue as reported in https://github.com/nteract/commuter/issues/298.
I'm setting the following environment variables:
```
COMMUTER_S3_KEY=<key>
COMMUTER_S3_SECRET=<secret>
COMMUTER_BUCKET=<bucket>
COMMUTER_STORAGE_BACKEND=s3
```
I independently tested that I have List and Get permissions on the bucket in question using `awscli`.
Below is the full stack trace that I receive when accessing `/view`. What stood out is the empty string that comes after the `<bucket>.`. As soon as I changed the default from `""` to `null` as per @elvinx's suggestion, it worked for me!
```
getaddrinfo ENOTFOUND <bucket>.
```
```
[Error [AjaxError]: ajax error 500] { 
xhr: { 
UNSENT: 0, 
OPENED: 1, 
HEADERS_RECEIVED: 2, 
LOADING: 3, 
DONE: 4, 
readyState: 4, 
onreadystatechange: [Function: …
```
> Change default value for COMMUTER_S3_ENDPOINT from empty string to null

- README.md
- src/backend/config.js
`CredentialProviderChain` [1] provides a number of different options on how to configure AWS credentials.
Changes:
- Use CredentialProviderChain if `COMMUTER_S3_KEY` and `COMMUTER_S3_SECRET` is not set
- Mark `COMMUTER_S3_KEY` and `COMMUTER_S3_SECRET` as deprecated in favour of `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
**TODO:**
[1] https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CredentialProviderChain.html
> [S3] Add support for common credentials config

- src/components/contents/html.js
When viewing a html document in commuter (such as a html rendered from a notebook through nbconvert), any links in the document will fail to open with an error like
```
about:srcdoc:1 Blocked opening 'https://example.com/' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.
```
This PR changes the Iframe permissions to allow links to work. Any concerns with this? Thanks!
> Allow links to open in html documents
