README.md, packages/commuter-server/config.js, packages/commuter-server/server.js
* Adhere to coding convention for env variables
=> Use upper case convention for environment variables

package.json, packages/commuter-breadcrumb/src/BreadCrumb.js, packages/commuter-dashboard/src/Dashboard.js, packages/commuter-dashboard/src/components/Table.js, packages/commuter-server/src/routes/util.js, packages/commuter-server/src/services/s3.js, packages/commuter-server/test/routesUtiltest.js, packages/commuter-server/test/s3test.js
* Use `listObjectsV2` method from `aws-sdk`
* Add `home` link to breadcrum nav bar
* Empty paths are handled as root dir path 
* Prop types for sanity
=> use newer `listObjectsV2` method and add prop types

.travis.yml, Procfile, README.md, package.json, packages/commuter-cli/package.json, packages/commuter-cli/src/index.js, packages/commuter-client/src/config.js, packages/commuter-directory-listing/src/components/Table.js, packages/commuter-server/src/config.js, packages/commuter-server/src/routes/contents.js, packages/commuter-server/src/services/s3.js
- [Commuter demo](https://nteract-commuter.herokuapp.com/)
- Deployment friendly config changes
- Add Heroku Procfile
=> Demo link + clean up and config changes for deployment

README.md
- Heroku is configured to do a deployment as soon as Travis build is passed and the branch is merged into master.
=> Add heroku deploy badge + automatic deploys

README.md, package.json, packages/commuter-breadcrumb/package.json, packages/commuter-cli/package.json, packages/commuter-directory-listing/package.json, packages/commuter-server/package.json
- Automate builds and browser refresh when lerna package src changes via `npm run start:watch`
- This will be little cleaner once this [PR](https://github.com/lerna/lerna/pull/255) is merged in lerna
=> Watch for component changes - auto build and browser refresh

README.md
- Reorder badges
- Use svg heroku badge
=> Cleanup badges

README.md
=> Update status of `Render page using notebook-preview` task

packages/commuter-cli/src/index.js, packages/commuter-client/src/Preview.js, packages/commuter-server/src/routes/index.js, packages/commuter-server/src/server.js
- So that this url's like [this](https://nteract-commuter.herokuapp.com/notebooks/IQR.ipynb) loads directly.
=> Bug fix: express route handling

packages/commuter-cli/src/index.js
There's no `@nteract` in the path for the local directory version.
=> fix(cli): local run has different path than prod

package.json, packages/commuter-cli/src/index.js, packages/commuter-server/src/routes/index.js, packages/commuter-server/src/server.js
- Fix prettier glob expansion issue
=> Better location for `build dir` when server running in production mode

README.md
- New updated images showcasing directory listing and notebook rendered view.
=> Add new images for the dashboard and notebook rendered view

packages/commuter-directory-listing/src/components/Table.js
- Render api data `pandas/tips/` -> `https://nteract-commuter.herokuapp.com/pandas/tips/`
=> For directory listing using relative path

README.md, packages/commuter-client/package.json, packages/commuter-client/src/Notebook.js
:boom: Now using nteract/nteract's components from the monorepo explosion! :boom:
=> Rely on core nteract components

packages/commuter-directory-listing/src/DirectoryListing.js, packages/commuter-server/src/services/s3.js, packages/commuter-server/test/s3test.js
- Use consistent paths (relative)  via API
=> Bug fix: Use Consistent paths for directory and files

packages/commuter-breadcrumb/.babelrc, packages/commuter-breadcrumb/package.json, packages/commuter-cli/.babelrc, packages/commuter-cli/package.json, packages/commuter-directory-listing/.babelrc, packages/commuter-directory-listing/package.json
=> Move babel config to package.json

packages/commuter-cli/package.json
Published package had the wrong path.
=> main binary is in lib/index.js

packages/commuter-cli/src/index.js, packages/commuter-client/src/App.js, packages/commuter-client/src/Notebook.js
- By this, we are able to run commuter server inside a docker container, locally and on Heroku via lerna symlinks via `commuter-cli`
=> Fix `comuter_client/server` module path resolution issue

packages/commuter-server/src/routes/index.js
- Endpoint to determine commuter API health.
=> API health check end point

packages/commuter-server/src/routes/discovery.js, packages/commuter-server/src/routes/index.js
- Returns mocked data for `api/v1/discovery`
=> placeholder data/api route for discovery

README.md, packages/commuter-server/README.md, packages/commuter-server/package.json, packages/commuter-server/src/config.js, packages/commuter-server/src/resources/commuter.es.mapping.json, packages/commuter-server/src/resources/generateMapping.js, packages/commuter-server/src/resources/nteract.metadata.schema.json, packages/commuter-server/src/routes/contents.js, packages/commuter-server/src/routes/discovery.js, packages/commuter-server/src/services/elasticSearch.js
- Load discovery notebooks from elastic index
- New mapping file `commuter.es.mapping.json` for `api/v1/discovery`
- `generateMapping.js` script to create `commuter.es.mapping.json` file
- New config env variable `COMMUTER_ES_HOST` to set elastic host
=> API to list discovery notebooks from ES backend

packages/commuter-client/src/Discovery.js
=> Style the gallery view more like the mockup

README.md, package.json, packages/commuter-cli/package.json, packages/commuter-server/src/routes/contents.js, packages/commuter-server/src/server.js, packages/commuter-server/src/services/s3.js, packages/commuter-server/test/s3test.js
- API to delete files and directories (recursively)
- API to upload file
- Start server in `watch` mode
=> Implement s3 upload/delete API

packages/commuter-server/src/resources/commuter.es.mapping.json, packages/commuter-server/src/resources/generateMapping.js, packages/commuter-server/src/services/elasticSearch.js
- Match `authors` type to `nbformat`
=> Match nbformat `authors type` to commuter es schema

packages/commuter-client/src/Notebook.js, packages/commuter-client/src/actions/index.js, packages/commuter-client/src/reducers/index.js, packages/commuter-client/src/store/preloadedState.js, packages/commuter-server/src/services/s3.js, packages/commuter-server/test/s3test.js
This fixes #79. After this goes in, I'll be simplifying this a little bit as I set up "renderers" for other content.
=> Adapt to contents API

packages/commuter-server/src/routes/files.js, packages/commuter-server/src/routes/index.js, packages/commuter-server/src/routes/view.js, packages/commuter-server/src/services/s3.js
rebasing my `render-more` PR was getting annoying
=> chore: run prettier through code base

packages/commuter-client/package.json
Brings in CSS changes, including fully expanded displays.
=> bump notebook preview

packages/commuter-breadcrumb/src/BreadCrumb.js, packages/commuter-client/src/Commuter.js, packages/commuter-server/src/services/elasticSearch.js
- Make `basePath` prefix breadcrumb navigation work
- Run `prettier`
=> Take `basePath` into account  for breadcrumb navigation

packages/commuter-breadcrumb/__tests__/BreadCrumb.test.js, packages/commuter-breadcrumb/__tests__/__snapshots__/BreadCrumb.test.js.snap, packages/commuter-breadcrumb/package.json
Adds Jest and some tests for the BreadCrumb component.
=> Add tests for BreadCrumb

README.md
@rgbkrk Thought I would take a swipe at connecting the name to the project's function.
=> Add intro about commuter to README

packages/commuter-client/src/Contents.js
=> expand json by default

packages/commuter-client/package.json
This brings in updates to notebook preview, most notably rendering of raw cells.
=> chore: upgrade nbp and normalize.css

CODE_OF_CONDUCT.md, LICENSE, README.md, ROADMAP.md
- Detailed setup instructions
- Updated license & roadmap
- Package publish details
=> Improve documentation

packages/commuter-client/public/index.html, packages/commuter-client/src/App.js, packages/commuter-client/src/Contents.js, packages/commuter-client/src/stylesheets/commuter.js, packages/commuter-directory-listing/src/DirectoryListing.js
Based on feedback about our margins from two separate groups.
=> Make iframe take up entire page

package.json
=> Run lerna init along with bootstrap

packages/commuter-cli/package.json
fixes #80 by failing early and loudly
=> Kill other processes if one exits or dies

packages/commuter-client/src/stylesheets/commuter.js
=> Even out view padding

packages/commuter-directory-listing/src/DirectoryListing.js
=> chore(DirListing): hide hidden files

packages/commuter-server/package.json, packages/commuter-server/src/config.js, packages/commuter-server/src/resources/generateMapping.js, packages/commuter-server/src/routes/api/contents.js, packages/commuter-server/src/routes/api/index.js, packages/commuter-server/src/routes/api/v1/discovery.js, packages/commuter-server/src/routes/files.js, packages/commuter-server/src/routes/index.js, packages/commuter-server/src/routes/util.js, packages/commuter-server/src/routes/view.js, packages/commuter-server/src/server.js, packages/commuter-server/src/services/elasticSearch.js, packages/commuter-server/src/services/s3.js
This completes the flow typing started in #140 to make it easier to refactor this without breaking changes.
=> fully flow type commuter server

packages/commuter-client/src/contents/strip-view.js, packages/commuter-client/src/reducers/index.js
=> fix content reducer and view stripping

package.json, packages/commuter-breadcrumb/package.json, packages/commuter-cli/package.json, packages/commuter-client/package.json, packages/commuter-directory-listing/package.json, packages/commuter-server/.babelrc, packages/commuter-server/package.json
=> pre[commit/push] hooks: flow, test and prettier

packages/commuter-client/src/contents/index.js
More left behinds from the switch of the paths to a leading relative path.
=> Fix files redirect

packages/commuter-server/src/content-providers/base/index.js, packages/commuter-server/src/content-providers/local/contents.js, packages/commuter-server/src/content-providers/local/fs.js
Partial solution to #161, allows directories to list files that have a symlink in them.
=> handle fs exceptions on the local content provider

README.md, package.json, packages/commuter-cli/README.md
Bring us up to date with all the new environment variables + the local mode.
=> Document all the new options

lerna.json, package.json
I've had this commit sitting here for a bit, time to get our lerna upgraded. 😄
=> prep us for the coming 2.0.0 release

packages/commuter-client/package.json
=> ⬆️  upgrade dependencies, primarily for code hiding

packages/commuter-client/src/contents/index.js
Applied on top of #175, merge that first.
Pretty basic, better than the blank screen we have.
=> Provide default renderer

packages/commuter-server/src/content-providers/local/files.js
Without this, the entire server would come crashing down when a file was not able to be accessed via the `/files/` endpoint. Very common for when relative images don't exist in a user's notebook.
:boom:
=> fix(local): files endpoint must handle errors

Procfile, package.json, packages/server/package.json
Fix the heroku setup, (re)introduce the commuter command line
=> Heroku production

package.json
Current nteract + immutable are running into issues with flow. Until those are resolved lets remove the pain here.
=> remove prepush until flow issues fixed

package.json, packages/frontend/index.js, packages/server/src/index.js
Catch errors on the promise chain for initial server start.
=> Failsafe log

packages/frontend/components/contents/index.js, packages/frontend/package-lock.json, packages/frontend/package.json
update source to latest version
=> Add plotly transforms to commuter

package.json, packages/frontend/components/body.js, packages/frontend/components/bread-crumb.js, packages/frontend/components/contents/zeppelin.js, packages/frontend/components/header.js, packages/frontend/package-lock.json, packages/frontend/package.json, packages/frontend/pages/_document.js, packages/frontend/pages/discover.js, packages/frontend/pages/view.js, packages/frontend/static/commuter.css
=> Migrate css to global use

packages/frontend/package-lock.json, packages/frontend/pages/_document.js
It was removed as a dependency in #200
=> Take out leftover styled-jsx

package-lock.json, packages/frontend/components/contents/index.js, packages/frontend/package-lock.json, packages/frontend/pages/_document.js, packages/frontend/transforms/PlotlyTransform.js, packages/frontend/transforms/index.js, packages/server/examples/display-plotly.ipynb, packages/server/package-lock.json
Adding a Plotly transform to handle the `application/vnd.plotly.v1+json` mimetype.
Closes: #165
=> Add Plotly transform

packages/frontend/components/contents/zeppelin.js
This handles the cases when zeppelin has a `results` Object as well as the older tab separate values case.
=> handle older zeppelin notebook formats

flow-typed/npm/jquery_v3.x.x.js, packages/frontend/components/contents/index.js, packages/frontend/package-lock.json, packages/frontend/package.json
=> cave in and provide jquery

packages/frontend/components/contents/index.js, packages/frontend/package-lock.json, packages/frontend/package.json
Support the officially declared vega mimetypes.
=> provide vega* in the commuter renderer

README.md
Couldn't help myself, the text I put in was ugly.
=> Make a now badge

packages/frontend/components/browse-header.js, packages/frontend/pages/view.js
=> feat: provide a way to download files with a link

packages/frontend/components/browse-header.js, packages/frontend/theme.js
Noticed I left some `console` and that the replace could be tightened up.
=> little bit of cleanup from #220

packages/server/src/content-providers/s3/contents.js
Doing a 'get' on a folder will now attempt to add a trailing slash if one is missing.
=> S3: Doing a 'get' on a folder will now attempt to add a trailing slash

packages/frontend/components/contents/directory-listing.js
One quick little fix for the directory listing.
=> prevent the time-ago from hugging the edge

package.json
bumping version of `transform-vega` to `6.0.1`
=> transform-vega-6.0.1

README.md
=> Modify README.md to add the 'gcs' option to COMMUTER_STORAGE_BACKEND

backend/content-providers/gcs/gcs.js
* Modify isNotebook to deal with GCS responses
* To show notebook contents on the view page
1. Run `env COMMUTER_STORAGE_BACKEND=gcs COMMUTER_BUCKET=commuter-shotarok-dev yarn dev`
1. Open http://localhost:4000/view/style_transfer/0.ipynb
=> Modify isNotebook to deal with GCS responses

backend/config.js
Fixes https://github.com/nteract/commuter/issues/294
=> Remove unnecessary PORT

Dockerfile
Fixes https://github.com/nteract/commuter/issues/297
=> Correct paths for static assets
